MYSQL_CONFIG_FILE: C:\xampp\mysql\data\my.ini
MYSQL_SERVER_ID_MASTER: 1
MYSQL_SERVER_ID_SLAVE: 2
MYSQL_DB_NAME: "vb_cms"
MYSQL_REPLICA_USER: "replica_user"
MYSQL_MASTER_HOST: 192.168.10.24
MYSQL_ROOT_USER: ansible
