- name: Ensure the directory TactileModelController is present
  ansible.windows.win_file:
    path: C:\ViewBoston\Utils\TactileModelController
    state: directory
  tags:
    - package

- name: Copy config file for Tactile Model Controller
  ansible.windows.win_copy:
    remote_src: true
    src: \\192.168.10.26\ViewBoston\Utils\_config\TactileModelController.env
    dest: C:\ViewBoston\Utils\TactileModelController\.env
  become: true
  become_method: runas
  become_flags: logon_type=new_credentials logon_flags=netcredentials_only
  vars:
    ansible_become_user: vb
    ansible_become_pass: View
  tags:
    - configuration

# Configuration for tactile
- name: modify CMS_SCAN_SOURCE configuration per hosts
  community.windows.win_lineinfile:
    path: C:\ViewBoston\Utils\TactileModelController\.env
    regex: '^CMS_SCAN_SOURCE='
    state: present
    backup: true
    create: true
    line: "CMS_SCAN_SOURCE={{ TACTILECONTROLLER.CMS_SCAN_SOURCE[inventory_hostname] }}"
  register: lineresult
  tags:
    - configuration
    - electron

- name: modify LANDMARKS configuration per hosts
  community.windows.win_lineinfile:
    path: C:\ViewBoston\Utils\TactileModelController\.env
    regex: '^LANDMARKS='
    state: present
    backup: true
    create: true
    line: "LANDMARKS={{ TACTILECONTROLLER.LANDMARKS[inventory_hostname] }}"
  register: lineresult
  tags:
    - configuration
    - electron

- name: modify CMS_API_ROOT configuration per hosts
  community.windows.win_lineinfile:
    path: C:\ViewBoston\Utils\TactileModelController\.env
    regex: '^CMS_API_ROOT='
    state: present
    backup: true
    create: true
    line: "CMS_API_ROOT={{ CMS_API_ROOT }}"
  register: lineresult
  tags:
    - configuration
    - electron

- name: Delete package-lock.json
  ansible.windows.win_file:
    path: C:\ViewBoston\Utils\TactileModelController\package-lock.json
    state: absent

- name: Install npm packages
  ansible.windows.win_shell: 'npm i'
  args:
    chdir: C:\ViewBoston\Utils\TactileModelController
  become: true
  become_method: runas
  become_flags: logon_type=new_credentials logon_flags=netcredentials_only
  vars:
    ansible_become_user: vb
    ansible_become_pass: View
## TactileModelController is launched by PM2


#"C:\Program Files\VideoLAN\VLC\vlc.exe" -I http --extraintf=http --http-host=0.0.0.0 --http-port=8080 --http-password=viewboston
# This task install vlc from Chocolatey
- name: Ensure vlc is installed through Chocolatey
  win_chocolatey:
    name: vlc
    state: present
  tags:
    - package

- name: Copy vlc batch file
  ansible.windows.win_copy:
    remote_src: true
    src: \\192.168.10.26\ViewBoston\Utils\start-vlc-tactile.bat
    dest: C:\ViewBoston\Utils\start-vlc-tactile.bat
  become: true
  become_method: runas
  become_flags: logon_type=new_credentials logon_flags=netcredentials_only
  vars:
    ansible_become_user: vb
    ansible_become_pass: View
  tags:
    - configuration

- name: Create a scheduled task launch VLC fullscreen on startup
  community.windows.win_scheduled_task:
    name: VLC
    description: Start VLC
    actions:
      - path: C:\ViewBoston\Utils\start-vlc-tactile.bat
    triggers:
    - type: logon
    username: vb
    runlevel: highest
    state: present
    enabled: yes
  tags:
    - configuration