- name: Ensure the directory TactileModelController is present
  ansible.windows.win_file:
    path: C:\ViewBoston\Utils\TactileModelController
    state: directory
  tags:
    - package

- name: Copy config file for Tactile Model Controller
  ansible.windows.win_copy:
    remote_src: true
    src: \\192.168.10.26\ViewBoston\Utils\_config\TactileModelController.env
    dest: C:\ViewBoston\Utils\TactileModelController\.env
  become: true
  become_method: runas
  become_flags: logon_type=new_credentials logon_flags=netcredentials_only
  vars:
    ansible_become_user: vb
    ansible_become_pass: View
  tags:
    - configuration

# Configuration for tactile
- name: modify CMS_SCAN_SOURCE configuration per hosts
  community.windows.win_lineinfile:
    path: C:\ViewBoston\Utils\TactileModelController\.env
    regex: '^CMS_SCAN_SOURCE='
    state: present
    backup: true
    create: true
    line: "CMS_SCAN_SOURCE={{ TACTILECONTROLLER.CMS_SCAN_SOURCE[inventory_hostname] }}"
  register: lineresult
  tags:
    - configuration
    - electron

- name: modify LANDMARKS configuration per hosts
  community.windows.win_lineinfile:
    path: C:\ViewBoston\Utils\TactileModelController\.env
    regex: '^LANDMARKS='
    state: present
    create: true
    line: "LANDMARKS={{ TACTILECONTROLLER.LANDMARKS[inventory_hostname] }}"
  register: lineresult
  tags:
    - configuration
    - electron

- name: modify CMS_API_ROOT configuration per hosts
  community.windows.win_lineinfile:
    path: C:\ViewBoston\Utils\TactileModelController\.env
    regex: '^CMS_API_ROOT='
    state: present
    create: true
    line: "CMS_API_ROOT={{ CMS_API_ROOT }}"
  register: lineresult
  tags:
    - configuration
    - electron



# VLC_IPADDRESS : default "localhost"
- name: modify VLC_IPADDRESS configuration per hosts
  community.windows.win_lineinfile:
    path: C:\ViewBoston\Utils\TactileModelController\.env
    regex: '^VLC_IPADDRESS='
    state: present
    create: true
    line: "VLC_IPADDRESS={{ TACTILECONTROLLER.VLC_IPADDRESS }}"
  register: lineresult
  tags:
    - configuration
    - electron
  
# VLC_PORT : default 8080
- name: modify VLC_PORT configuration per hosts
  community.windows.win_lineinfile:
    path: C:\ViewBoston\Utils\TactileModelController\.env
    regex: '^VLC_PORT='
    state: present
    create: true
    line: "VLC_PORT={{ TACTILECONTROLLER.VLC_PORT }}"
  register: lineresult
  tags:
    - configuration
    - electron
  
# VLC_PASSWORD : default "viewboston"
- name: modify VLC_PASSWORD configuration per hosts
  community.windows.win_lineinfile:
    path: C:\ViewBoston\Utils\TactileModelController\.env
    regex: '^VLC_PASSWORD='
    state: present

    create: true
    line: "VLC_PASSWORD={{ TACTILECONTROLLER.VLC_PASSWORD }}"
  register: lineresult
  tags:
    - configuration
    - electron

# VLC_VOLUME : default 100 [1-100]
- name: modify VLC_VOLUME configuration per hosts
  community.windows.win_lineinfile:
    path: C:\ViewBoston\Utils\TactileModelController\.env
    regex: '^VLC_VOLUME='
    state: present
    backup: true
    create: true
    line: "VLC_VOLUME={{ TACTILECONTROLLER.VLC_VOLUME }}"
  register: lineresult
  tags:
    - configuration
    - electron


- name: Delete package-lock.json
  ansible.windows.win_file:
    path: C:\ViewBoston\Utils\TactileModelController\package-lock.json
    state: absent

- name: Install npm packages
  ansible.windows.win_shell: 'npm i'
  args:
    chdir: C:\ViewBoston\Utils\TactileModelController
  become: true
  become_method: runas
  become_flags: logon_type=new_credentials logon_flags=netcredentials_only
  vars:
    ansible_become_user: vb
    ansible_become_pass: View
## TactileModelController is launched by PM2


