---
# Playbook for cms server system deployement
- hosts: 
    - cms
  roles:
    - common
    - zerotier
    - cms

- name: Include the replication playbook
  include: playbooks/mysql-replication.yml