#"C:\Program Files\VideoLAN\VLC\vlc.exe" "C:\ViewBoston\Misc\Preshow\_PreShow_Edit_vA_v221209a.mov" --fullscreen --no-mouse-events --loop --no-osd --no-audio --extraintf=http --http-host=0.0.0.0 --http-port=8080 
#--http-password=vlc
# This task install vlc from Chocolatey
- name: Ensure nodejs is installed through Chocolatey
  win_chocolatey:
    name: vlc
    state: present
  tags:
    - package

- name: Ensure the media directory is present
  ansible.windows.win_file:
    path: C:\ViewBoston\Misc\Preshow
    state: directory
  tags:
    - package

- name: Copy config media file
  ansible.windows.win_copy:
    remote_src: true
    src: \\192.168.10.26\ViewBoston\Misc\Preshow\_PreShow_Edit_vA_v221209a.mov
    dest: C:\ViewBoston\Misc\Preshow\_PreShow_Edit_vA_v221209a.mov
  become: true
  become_method: runas
  become_flags: logon_type=new_credentials logon_flags=netcredentials_only
  vars:
    ansible_become_user: vb
    ansible_become_pass: View
  tags:
    - configuration

- name: Create a scheduled task launch VLC fullscreen on startup
  community.windows.win_scheduled_task:
    name: VLC
    description: Start VLC
    actions:
      - path: start
        arguments: 
          C:\Program Files\VideoLAN\VLC\vlc.exe
          C:\ViewBoston\Misc\Preshow\_PreShow_Edit_vA_v221209a.mov
          --fullscreen
          --no-mouse-events 
          --loop
          --no-osd
          --no-audio
          --extraintf=http
          --http-host=0.0.0.0
          --http-port=8080
      #-path: powershell

    triggers:
    - type: logon
    username: vb
    runlevel: highest
    state: present
    enabled: yes