# This task install nodejs from Chocolatey

- name: Install NodeJS via electron
  throttle: 1
  block: 
  - name: Ensure nodejs is installed through Chocolatey
    win_chocolatey:
      name: nodejs
      state: present
    throttle: 1
    notify: restart-computer

# Allow nodejs through
- name: Firewall rule to allow NodeJS
  community.windows.win_firewall_rule:
    name: NodeJS
    action: allow
    direction: in
    protocol: tcp
    program: C:\Program Files\nodejs\node.exe
    profiles: domain,private,public
    state: present
    enabled: yes

- name: Sleep for 3 seconds for Chocolatey Rate-Limits respect
  ansible.builtin.wait_for:
    timeout: 3
  delegate_to: localhost

#Install PM2
- name: Install "PM2" node.js package globally.
  win_shell: npm install pm2 -g
  when: inventory_hostname != 'dvs06_01'

#Apply reboot handler if needed
- meta: flush_handlers

