#Configure PM2 by loading the different config files.

- name: Load service configuration file in PM2
  ansible.windows.win_shell: '"c:\Users\{{ ansible_user }}\AppData\Roaming\npm\pm2.cmd" start {{ pm2_config_file }}'
  args:
    executable: cmd
    chdir: C:\ViewBoston\Utils
  async: 10
  ignore_errors: true
    # when: inventory_hostname != 'dvs06_01'

- name: Save configuration for PM2
  ansible.windows.win_shell: '"C:\Users\{{ ansible_user }}\AppData\Roaming\npm\pm2.cmd" save'
  args:
    executable: cmd
    chdir: C:\ViewBoston\Utils
  async: 10
  ignore_errors: true
    #when: inventory_hostname != 'dvs06_01'
  
- name: Create batch file
  ansible.windows.win_copy:
    dest: C:\ViewBoston\Utils\start-pm2.bat
    content: |
      %windir%\system32\CMD.exe /k "start pm2 resurrect"

- name: Create a scheduled task launch pm2
  community.windows.win_scheduled_task:
    name: PM2
    description: restart all PM2 services
    actions:
    - path: C:\ViewBoston\Utils\start-pm2.bat
      arguments: 
    triggers:
    - type: logon
    username: "{{ ansible_user }}"
    runlevel: highest
    state: present
    enabled: yes
