
- name: Ensure the directory RotaryEncoderProcessor is present
  ansible.windows.win_file:
    path: C:\ViewBoston\Utils\RotaryEncoderProcessor
    state: directory
  tags:
    - configuration

- name: Copy config file for Rotary Encoder Processor
  ansible.windows.win_copy:
    remote_src: true
    src: \\192.168.10.26\ViewBoston\Utils\_config\RotaryEncoder.json
    dest: C:\ViewBoston\Utils\RotaryEncoderProcessor\config.json
  become: true
  become_method: runas
  become_flags: logon_type=new_credentials logon_flags=netcredentials_only
  vars:
    ansible_become_user: vb
    ansible_become_pass: View
  tags:
    - configuration

# Rotary Encoder Processor Configuration
# CalibrationOffset: int 0 to 3600
#	"OSCChannel":"/sensor/slider1"
#	"SerialBusBaudRate":115200
#	"SensorPollIntervalMilliseconds":10
#	"DivideValuesBy":3600.0

- name: Set filepath
  set_fact:
    rotary_encoder_config_path: C:\ViewBoston\Utils\RotaryEncoderProcessor\config.json
- name: Read Rotary Encoder Processor Config file
  ansible.builtin.slurp:
    src: "{{ rotary_encoder_config_path }}"
  register: current_file
- name: modify more key/values
  set_fact:
    current_payload: "{{ current_file['content'] | b64decode }}"
- name: Change Callibration Offset per machine
  set_fact:
    modified_payload: "{{ current_payload | default([]) | combine({ 'CalibrationOffset': ROTARY.CalibrationOffset[inventory_hostname] }) }}"
- name: Change SerialBusBaudRate
  set_fact:
    modified_payload: "{{ modified_payload | default([]) | combine({ 'SerialBusBaudRate': ROTARY.SerialBusBaudRate }) }}"
- name: Change OSCChannel
  set_fact:
    modified_payload: "{{ modified_payload | default([]) | combine({ 'OSCChannel': ROTARY.OSCChannel }) }}"
- name: Change SensorPollIntervalMilliseconds
  set_fact:
    modified_payload: "{{ modified_payload | default([]) | combine({ 'SensorPollIntervalMilliseconds': ROTARY.SensorPollIntervalMilliseconds }) }}"
- name: Change DivideValuesBy
  set_fact:
    modified_payload: "{{ modified_payload | default([]) | combine({ 'DivideValuesBy': ROTARY.DivideValuesBy }) }}"
- name: write vars back to file
  ansible.windows.win_copy: 
    content: "{{ modified_payload | to_nice_json }}" 
    dest:  "{{ rotary_encoder_config_path }}"

- name: Making sure NSSM is installed for the service configuration
  win_chocolatey:
    name: nssm
    state: present

# Install the RotaryEncoder service, and then configure and start it with win_service
- name: Install the RotaryEncoder service, redirecting stdout and stderr a log file in the same directory
  win_nssm:
    name: RotaryEncoder
    application: C:\ViewBoston\Utils\RotaryEncoderProcessor\RotaryEncoderProcessor.exe
    stdout_file: C:\ViewBoston\Utils\RotaryEncoderProcessor\RotaryEncoder.log
    stderr_file: C:\ViewBoston\Utils\RotaryEncoderProcessor\RotaryEncoder.log

- name: Stop the RotaryEncoder service
  win_service:
    name: RotaryEncoder
    state: stopped
  ignore_errors: true
- name: Start the RotaryEncoder service
  win_service:
    name: RotaryEncoder
    state: started
  ignore_errors: true