# 7th Sense : 7780
- name: Firewall rule to allow 7th sense traffic on 7780/TCP
  community.windows.win_firewall_rule:
    name: 7th Sense
    localport: 7780
    action: allow
    direction: in
    protocol: tcp
    profiles: domain,private,public
    state: present
    enabled: yes