---
# Playbook to setup videoservers
- name: Import subtasks task
  include_tasks: "{{ item }}"
  loop:
    - firewall-videoserver.yml
    - deploy-base-dir.yml
    - file-extensions.yml
    - set-hostname.yml
    - set-hosts-file.yml