---
# Install ASP.NET Core Runtime 6.0.0. Hosting Bundle
# https://dotnet.microsoft.com/en-us/download/dotnet/thank-you/runtime-aspnetcore-6.0.0-windows-hosting-bundle-installer
- name: Create temporary build directory
  ansible.windows.win_tempfile:
    state: directory
    suffix: installers
  register: result

- debug:
    msg: "Copied installer to {{ result.path }}"

- name: Copy ASP.NET Core Runtime 6.0.0. Hosting Bundle to temp directory
  ansible.windows.win_copy:
    src: ../../packages/dotnet-hosting-6.0.0-win.exe
    dest: '{{result.path}}\'
- name: Install ASP.NET Core Runtime 6.0.0. Hosting Bundle
  ansible.windows.win_package:
    path: '{{result.path}}\dotnet-hosting-6.0.0-win.exe'
    arguments: /quiet /install
    product_id: '{120E0990-DDCC-456B-8B29-0BDD2D82C4EA}'
    state: present
  ignore_errors: true

#Product Ids for all installed components
#{120E0990-DDCC-456B-8B29-0BDD2D82C4EA} Microsoft .NET Host - 6.0.0 (x64)                              C:\Windows\Ins...
#{848535A5-5097-48F6-801A-5D165017FC26} Microsoft .NET Host - 6.0.0 (x86)                              C:\Windows\Ins...
#{740DEBEB-4049-4179-AF82-673DE9E7F52E} Microsoft .NET Host FX Resolver - 6.0.0 (x64)                  C:\Windows\Ins...
#{BC30BB3F-4E4F-42EA-B4CD-906B38B5EFB9} Microsoft .NET Host FX Resolver - 6.0.0 (x86)                  C:\Windows\Ins...
#{0875A1B4-8C93-48C7-BEC9-4E549B550B1B} Microsoft .NET Runtime - 6.0.0 (x64)                           C:\Windows\Ins...
#{FDCEC40E-88CC-4E8A-BF27-E375F3F8A0CE} Microsoft .NET Runtime - 6.0.0 (x86)                           C:\Windows\Ins...
#{A244158E-3897-3054-87D9-666E676D77DB} Microsoft ASP.NET Core 6.0.0 Shared Framework (x64)            C:\Windows\Ins...
#{81586DBF-DB63-384E-BCCD-FCCE31146664} Microsoft ASP.NET Core 6.0.0 Shared Framework (x86)