---
# This task install bginfo from Chocolatey
vars:
  filepath: '{{view_win_base_path}}\Utils'
tasks:
- name: Ensure bginfo is installed through Chocolatey
  win_chocolatey:
    name: bginfo
    state: present
- name: Ensure directory is present
  ansible.windows.win_file:
    path: "{{ filepath }}"
    state: directory
- name: Copy a single file keeping the filename
  ansible.windows.win_copy:
    src: ../resources/bgconf.bgi
    dest: "{{ filepath }}"
- name: Setup BGInfo
  #ansible.windows.win_shell: 'C:\ProgramData\chocolatey\bin\bginfo {{ filepath }}\bgconf.bgi /TIMER:0'
  ansible.windows.win_shell: 'C:\ProgramData\chocolatey\bin\bginfo C:\ViewBoston\Utils\bgconf.bgi /ALL /TIMER:0'
  args:
    chdir: 'C:\ProgramData\chocolatey\bin\'