---
# Install FTDI CDM Driver
# https://ftdichip.com/drivers/vcp-drivers/
- name: Create temporary build directory
  ansible.windows.win_tempfile:
    state: directory
    suffix: installers
  register: result

- debug:
    msg: "Copied installer to {{ result.path }}"

- name: Copy FTDI CDM Driver installer to temp directory
  ansible.windows.win_copy:
    src: packages/CDM212364_Setup.exe
    dest: '{{result.path}}\'
- name: Install FTDI CDM Driver
  ansible.windows.win_package:
    path: '{{result.path}}\CDM212364_Setup.exe'
    #product_id: '{DBDA69FB-7466-4FFC-B58B-35E7E7CBEDC9}'
    arguments: /qn /install
    state: present
  