---
# Playbook to enable Windows Auto-Logon
- name: Set autologon
  community.windows.win_auto_logon:
    username: "{{ ansible_user }}"
    password: "{{ ansible_password }}"
  tags:
    - configuration