# roles/common/tasks/main.yml
- name: Import subtasks task
  include_tasks: "{{ item }}"
  loop:
    #- netbox-collect.yml
    - set-hostname.yml
    - autologon.yml
    #- base-software.yml
    - power-settings.yml
    #- deploy-base-dir.yml
    - notifications.yml
    - touchscreen.yml
    - background.yml
  tags:
         - package
         - configuration