# Task to set audio volume with nircmd
- name: Copy nircmd executable to Windows32
  ansible.windows.win_copy:
    src: ../../packages/nircmd.exe
    dest: C:\Windows\system32\

- name: Set Volume with nircmd
  win_shell: "nircmd.exe setsysvolume {{ (AUDIO_VOLUME| int / 100 * 65535) | int  }}"
  when: AUDIO_VOLUME is defined