---
# Playbook to setup cacher controller
- name: Import subtasks task
  include_tasks: "{{ item }}"
  loop:
    - firewall-cacher.yml
    - deploy-cacher-controller.yml
  tags:
    - cacher_controller