---
# Playbook sto set audio volume with powershell
# Function Set-Speaker($Volume){$wshShell = new-object -com wscript.shell;1..50 | % {$wshShell.SendKeys([char]174)};1..$Volume | % {$wshShell.SendKeys([char]175)}}
#Sets volume to 60%
#Set-Speaker -Volume 30
#Sets volume to 80%
#Set-Speaker -Volume 40
#Sets volume to 100%
#Set-Speaker -Volume 50
- hosts: all
  tasks:
    - name: Set volume to {% set volume = volume | int  / 2 | default(50) | int  %} {{ volume * 2 }} %
      win_shell: |
        Function Set-Speaker($Volume){$wshShell = new-object -com wscript.shell;1..50 | % {$wshShell.SendKeys([char]174)};1..$Volume | % {$wshShell.SendKeys([char]175)}}; Set-Speaker -Volume 50
      when: volume is defined