---
#Configure PM2 by loading the different config files.
- hosts: all
  vars:
  tasks:
  - name: Load service configuration file in PM2
    ansible.windows.win_shell: 'C:\Users\vagrant\AppData\Roaming\npm\pm2.cmd start {{ pm2_config_file }}'
    args:
      chdir: C:\ViewBoston\Utils

  - name: Save configuration for PM2
    ansible.windows.win_shell: 'C:\Users\vagrant\AppData\Roaming\npm\pm2.cmd save'
    args:
      chdir: C:\ViewBoston\Utils
  - name: Create batch file
    ansible.windows.win_copy:
      dest: C:\ViewBoston\Utils\RequestCacher\start.bat
      content: |
        %windir%\system32\CMD.exe /k "start pm2 resurrect"

  - name: Create a scheduled task launch pm2
    community.windows.win_scheduled_task:
      name: PM2
      description: restart all PM2 services
      actions:
      - path: C:\ViewBoston\Utils\RequestCacher\start.bat
        arguments: 
      triggers:
      - type: logon
      username: vb
      runlevel: highest
      state: present
      enabled: yes

  - name: Reboot the machine with all defaults
    ansible.windows.win_reboot: