---
- hosts:
    - cms
    - storage
  tasks:
  - name: Enable RDP connections from PowerShell
    win_shell: |
      Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -name "fDenyTSConnections" -value 0

  - name: Firewall rule to allow RDP on TCP port 3389
    community.windows.win_firewall_rule:
      name: Remote Desktop
      localport: 3389
      action: allow
      direction: in
      protocol: tcp
      profiles: private
      state: present
      enabled: yes