---
# Rebbot hosts
- hosts: all
  tasks:
  - name: Change power plan to high performance
    community.windows.win_power_plan:
      name: high performance
      #name: balanced
    tags:
          - configuration
  # - name: Pause for 1 minute
  #   ansible.builtin.pause:
  #     minutes: 1

  - name: Set display timeout to disabled
    # Might need a restart
    ansible.windows.win_regedit:
      path: HKLM:\SYSTEM\CurrentControlSet\Control\Power\PowerSettings\7516b95f-f776-4464-8c53-06167f40cc99\3c0bc021-c8a8-4e07-a973-6b14cbcb2b7e\DefaultPowerSchemeValues\8c5e7fda-e8bf-4a96-9a85-a6e23a8c635c
      name: AcSettingIndex
      data: 0
      type: dword
  - name: Set display timeout to disabled      
    ansible.windows.win_regedit:
      path: HKLM:\SYSTEM\CurrentControlSet\Control\Power\PowerSettings\7516b95f-f776-4464-8c53-06167f40cc99\3c0bc021-c8a8-4e07-a973-6b14cbcb2b7e\DefaultPowerSchemeValues\8c5e7fda-e8bf-4a96-9a85-a6e23a8c635c
      name: ProvAcSettingIndex
      data: 0
      type: dword

  # - name: Reboot the machine with all defaults
  #   ansible.windows.win_reboot: