---
# This playbook configures the windows touchscreen settings
- hosts: all
  tasks:
  - name: Disable Edge Swipe
    ansible.windows.win_regedit:
      path: HKLM:\SOFTWARE\Policies\Microsoft\Windows\EdgeUI
      name: AllowEdgeSwipe
      data: 0
      type: dword
  - name: Disable touch visual feedback - contact
    ansible.windows.win_regedit:
      path: HKCU:\Control Panel\Cursors
      name: ContactVisualization
      data: 0
      type: dword
  - name: Disable touch visual feedback - gestures
    ansible.windows.win_regedit:
      path: HKCU:\Control Panel\Cursors
      name: GestureVisualization
      data: 0
      type: dword
  - name: Disable touch right-click
    ansible.windows.win_regedit:
      path: HKCU:\Software\Microsoft\Wisp\Touch
      name: TouchMode_hold
      data: 3
      type: dword