# Copy config to C:\Users\VB\AppData\Local\Programs\viewboston\.env
- name: Stop ViewBoston Process
  win_shell:  Stop-Process -Name "ViewBoston"
  ignore_errors: true
  tags:
    - configuration
    - electron

# - debug:
#     var: interactive_var_vals
#   tags:
#     - configuration
#     - electron

- name: Ensure the directory ViewBoston is present
  ansible.windows.win_file:
    path: C:\Users\VB\AppData\Local\Programs\viewboston\
    state: directory
  tags:
    - configuration
    - electron
    
- name: Copy base config file
  win_copy:
    remote_src: true
    src: \\192.168.10.26\ViewBoston\Electron\_config\.env
    dest: C:\Users\VB\AppData\Local\Programs\viewboston\.env
  become: true
  become_method: runas
  become_flags: logon_type=new_credentials logon_flags=netcredentials_only
  vars:
    ansible_become_user: vb
    ansible_become_pass: View
  tags:
    - configuration
    - electron

- name: Copy google API config file
  win_copy:
    remote_src: true
    src: \\192.168.10.26\ViewBoston\Electron\_config\google_app_credentials.json
    dest: C:\Users\VB\AppData\Local\Programs\viewboston\google_app_credentials.json
  become: true
  become_method: runas
  become_flags: logon_type=new_credentials logon_flags=netcredentials_only
  vars:
    ansible_become_user: vb
    ansible_become_pass: View
  tags:
    - configuration
    - electron

- name: Copy debug launcher file
  win_copy:
    remote_src: true
    src: \\192.168.10.26\ViewBoston\Electron\_config\rundebug.bat
    dest: C:\Users\VB\AppData\Local\Programs\viewboston\rundebug.bat
  become: true
  become_method: runas
  become_flags: logon_type=new_credentials logon_flags=netcredentials_only
  vars:
    ansible_become_user: vb
    ansible_become_pass: View
  tags:
    - configuration
    - electron

# Configuration for electron
# CMS_API_ROOT=http://192.168.10.27
- name: modify configuration per hosts
  community.windows.win_lineinfile:
    path: C:\Users\VB\AppData\Local\Programs\viewboston\.env
    regex: '^CMS_API_ROOT='
    state: present
    backup: false
    create: true
    line: "CMS_API_ROOT={{ ELECTRON.CMS_API_ROOT }}"
  register: lineresult
  tags:
    - configuration
    - electron

- name: modify route configuration
  community.windows.win_lineinfile:
    path: C:\Users\VB\AppData\Local\Programs\viewboston\.env
    regex: '^ROUTE='
    state: present
    backup: false
    create: true
    line: 'ROUTE={{ ELECTRON.ROUTE }}'
  tags:
    - configuration
    - electron

- name: modify content api cron job
  community.windows.win_lineinfile:
    path: C:\Users\VB\AppData\Local\Programs\viewboston\.env
    regex: '^CMS_API_GET_CONTENT_CRON='
    state: present
    backup: false
    create: true
    line: "CMS_API_GET_CONTENT_CRON={{ ELECTRON.CMS_API_GET_CONTENT_CRON[inventory_hostname] }}"
  register: lineresult
  tags:
    - configuration
    - electron

- name: modify settings api cron job
  community.windows.win_lineinfile:
    path: C:\Users\VB\AppData\Local\Programs\viewboston\.env
    regex: '^CMS_API_GET_SETTINGS_CRON='
    state: present
    backup: false
    create: true
    line: "CMS_API_GET_SETTINGS_CRON={{ ELECTRON.CMS_API_GET_SETTINGS_CRON[inventory_hostname] }}"
  register: lineresult
  tags:
    - configuration
    - electron

# Configuration for discover-boston
- name: modify configuration per hosts
  community.windows.win_lineinfile:
    path: C:\Users\VB\AppData\Local\Programs\viewboston\.env
    regex: '^DISCOVER_BOSTON_APP_SOURCE='
    state: present
    backup: false
    create: true
    line: "DISCOVER_BOSTON_APP_SOURCE={{ ELECTRON.DISCOVER_BOSTON_APP_SOURCE[inventory_hostname] }}"
  register: lineresult
  when: "'interactive' in group_names"
  tags:
    - configuration
    - electron

# Configuration for poster
# THEATER_POSTER_APP_SOURCE=theatre_poster_1
- name: modify configuration per hosts
  community.windows.win_lineinfile:
    path: C:\Users\VB\AppData\Local\Programs\viewboston\.env
    regex: '^THEATER_POSTER_APP_SOURCE='
    state: present
    backup: false
    create: true
    line: "THEATER_POSTER_APP_SOURCE={{ ELECTRON.THEATER_POSTER_APP_SOURCE[inventory_hostname] }}"
  register: lineresult
  when: "'poster' in group_names"
  tags:
    - configuration
    - electron


# Configuration for viewer
# VIRTUAL_VIEWER_APP_SOURCE=virtual_viewer_1
- name: modify configuration per hosts
  community.windows.win_lineinfile:
    path: C:\Users\VB\AppData\Local\Programs\viewboston\.env
    regex: '^VIRTUAL_VIEWER_APP_SOURCE='
    state: present
    backup: false
    create: true
    line: "VIRTUAL_VIEWER_APP_SOURCE={{ ELECTRON.VIRTUAL_VIEWER_APP_SOURCE[inventory_hostname] }}"
  register: lineresult
  when: "'viewer' in group_names"
  tags:
    - configuration
    - electron


# Configuration for finale
# FINALE_KIOSK_APP_SOURCE=finale_1
- name: modify configuration per hosts
  community.windows.win_lineinfile:
    path: C:\Users\VB\AppData\Local\Programs\viewboston\.env
    regex: '^FINALE_KIOSK_APP_SOURCE='
    state: present
    backup: false
    create: true
    line: "FINALE_KIOSK_APP_SOURCE={{ ELECTRON.FINALE_KIOSK_APP_SOURCE[inventory_hostname] }}"
  register: lineresult
  when: "'finale' in group_names"
  tags:
    - configuration
    - electron

# FINALE_KIOSK_SCAN_TICKET_POSITION=top
- name: modify finale scan position per hosts
  community.windows.win_lineinfile:
    path: C:\Users\VB\AppData\Local\Programs\viewboston\.env
    regex: '^FINALE_KIOSK_SCAN_TICKET_POSITION='
    state: present
    backup: false
    create: true
    line: "FINALE_KIOSK_SCAN_TICKET_POSITION={{ ELECTRON.FINALE_KIOSK_SCAN_TICKET_POSITION[inventory_hostname] }}"
  register: lineresult
  when: "'finale' in group_names"
  tags:
    - configuration
    - electron

# Configuration for viewer
# VV_PANORAMA_IMG=VV_Boston_Base_230320_Shadow3_Sky2.jpg
- name: modify configuration per hosts
  community.windows.win_lineinfile:
    path: C:\Users\VB\AppData\Local\Programs\viewboston\.env
    regex: '^VV_PANORAMA_IMG='
    state: present
    backup: false
    create: true
    line: "VV_PANORAMA_IMG={{ ELECTRON.VV_PANORAMA_IMG }}"
  register: lineresult
  when: "'viewer' in group_names"
  tags:
    - configuration
    - electron

