# Electron App : 1212, 5000, 7000
- name: Firewall rule to allow electron app traffic on 1212/TCP, 5000/TCP and 7000/TCP
  community.windows.win_firewall_rule:
    name: Electron App
    localport: 1212,5000,7000
    action: allow
    direction: in
    protocol: tcp
    profiles: domain,private,public
    state: present
    enabled: yes
